apply plugin: 'com.android.application'

android {
    namespace 'com.lisa.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.lisa.nexus"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "0.1"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}


dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"
    implementation files('libs/sherpa-onnx-1.13.5.aar')
    implementation 'com.github.mwiede:jsch:2.28.7'
}
